// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aefqxvxwbiqrwlynqufw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZnF4dnh3YmlxcndseW5xdWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDgzMzIsImV4cCI6MjA2ODMyNDMzMn0.tVe55722yyZsrdXYo1Pgr7K7WntHTMRqYMCYUxr8mEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});